name: build and test

on:
  push:
    branches:
      - master
    paths:
      - '**/*.cs'
      - '**/*.csproj'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.cs'
      - '**/*.csproj'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.203' # The .NET SDK version to use
  OWNER: 'ianphil' # The owner of the repository

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore lib/lib.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore lib/lib.sln
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal lib/lib.sln

  publish:
    name: Publish NuGet package
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore lib/lib.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore lib/lib.sln

    - name: Pack NuGet package
      run: dotnet pack lib/Idp.Lib.Tools/Idp.Lib.Tools.csproj --configuration Release --output ./nupkg

    - name: Publish NuGet package
      env:
        NUGET_API_KEY: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet nuget push ./nupkg/*.nupkg --source https://nuget.pkg.github.com/${{ env.OWNER }}/index.json --api-key ${{ secrets.GH_PACKAGES_TOKEN }} --skip-duplicate
